#!/usr/bin/env bash
# 0.4.0: consumer scripts may be Lua. The template justfile routes tool/build-script/update through
# run-script.sh; rewrite the three stock recipes if they are still the 0.2 shape. Adds generated Lua files to .gitignore.
set -euo pipefail
cd "$MONO_ROOT"
if [[ -f justfile ]]; then
  sed -i.bak \
    -e 's#^    @\./scripts/build/"\$1"\.sh "\${@:2}"$#    @"{{mono_home}}/scripts/tools/run-script.sh" build "$@"#' \
    -e 's#^    @\./scripts/tools/"\$1"\.sh "\${@:2}"$#    @"{{mono_home}}/scripts/tools/run-script.sh" tools "$@"#' \
    -e 's#^    @\./scripts/update/"\$1"\.sh "\${@:2}"$#    @"{{mono_home}}/scripts/tools/run-script.sh" update "$@"#' \
    justfile && rm -f justfile.bak
fi
if [[ -f .gitignore ]] && ! grep -q '^\.lua-meta/$' .gitignore; then
  printf '\n# Lua editor support and coverage, generated by just lua meta / just lua cover\n.luarc.json\n.lua-meta/\ncoverage.txt\ntrace.json\n' >> .gitignore
fi
if [[ -f .gitignore ]] && ! grep -q '^\.buckconfig\.local$' .gitignore; then
  printf '\n# this machine\x27s binary paths, which an app may write\n.buckconfig.local\n' >> .gitignore
fi
echo "  justfile routes scripts through run-script.sh; .gitignore covers generated Lua files"
