-- embed.lua OUT LANG SYMBOL INPUT
-- The input file as bytes in C or Rust source, so a host binary carries its Lua inline.
local out, lang, sym, input = arg[1], arg[2], arg[3], arg[4]
local f = assert(io.open(input, "rb"))
local data = f:read("a")
f:close()
local o = assert(io.open(out, "wb"))
local parts = {}
for i = 1, #data do
  parts[#parts + 1] = tostring(data:byte(i))
  if i % 24 == 0 then parts[#parts + 1] = "\n" end
end
local body = table.concat(parts, ","):gsub(",\n,", ",\n")
if lang == "c" then
  o:write(("/* generated by monomono lua_embed */\n#include <stddef.h>\nstatic const unsigned char %s[] = {\n%s\n};\nstatic const size_t %s_len = %d;\n"):format(sym, body, sym, #data))
elseif lang == "rust" then
  o:write(("// generated by monomono lua_embed\npub static %s: &[u8] = &[\n%s\n];\n"):format(sym:upper(), body))
else
  error("lang must be c or rust: " .. tostring(lang))
end
o:close()
