-- wasm.lua OUT BUNDLE NAME
-- An ES module for the browser: the bundle as a string plus a runner for wasmoon (Lua 5.4 in WebAssembly).
local out, bundle, name = arg[1], arg[2], arg[3]
local f = assert(io.open(bundle, "rb")); local src = f:read("*a"); f:close()
local esc = src:gsub("\\", "\\\\"):gsub("`", "\\`"):gsub("%${", "\\${")
local o = assert(io.open(out, "w"))
o:write(([[// generated by monomono lua_wasm — %s
// Usage (wasmoon): import { LuaFactory } from "wasmoon"; import { run } from "./%s.mjs";
//   const { engine, result } = await run(new LuaFactory());
export const name = %q;
export const source = `%s`;
export async function run(factory, { args = [], globals = {} } = {}) {
  const engine = await factory.createEngine();
  engine.global.set("arg", Object.assign([], args));
  for (const [k, v] of Object.entries(globals)) engine.global.set(k, v);
  const result = await engine.doString(source);
  return { engine, result };
}
]]):format(name, name, name, esc))
o:close()
