#!/usr/bin/env bash
# git/ci/github is the source of truth for workflows; .github/workflows is a generated copy.
# (GitHub does not follow symlinks for workflow files, so this is a copy, not a link.)

source "$(cd "$(dirname "$0")/.." && pwd)/lib.sh"

SRC="$MONO_CI/github"
DEST="$MONO_ROOT/.github/workflows"
CHECK="$MONO_CI/local/check.sh"

usage() {
  cat >&2 <<'USAGE'
usage:
  just ci sync      # copy git/ci/github/*.yml into .github/workflows
  just ci run       # run git/ci/local/check.sh (what CI runs)
  just ci status    # is .github/workflows current
USAGE
  exit 2
}

header() {
  echo "# generated by just ci sync from git/ci/github/$1 — edit the source, not this copy"
}

cmd_sync() {
  [[ -d $SRC ]] || die "missing $(rel "$SRC")"
  mkdir -p "$DEST"
  local f name
  for f in "$SRC"/*.yml "$SRC"/*.yaml; do
    [[ -f $f ]] || continue
    name=$(basename "$f")
    { header "$name"; cat "$f"; } >"$DEST/$name"
  done
  for f in "$DEST"/*.yml "$DEST"/*.yaml; do
    [[ -f $f ]] || continue
    name=$(basename "$f")
    [[ -f $SRC/$name ]] || rm -f "$f"
  done
  echo "synced .github/workflows from git/ci/github"
}

cmd_status() {
  local quiet=${1-} f name stale=0
  for f in "$SRC"/*.yml "$SRC"/*.yaml; do
    [[ -f $f ]] || continue
    name=$(basename "$f")
    if [[ ! -f $DEST/$name ]] || ! { header "$name"; cat "$f"; } | cmp -s - "$DEST/$name"; then
      [[ $quiet == --quiet ]] || echo "stale     $name"
      stale=$((stale + 1))
    else
      [[ $quiet == --quiet ]] || echo "current   $name"
    fi
  done
  [[ $stale -eq 0 ]]
}

cmd_run() {
  [[ -f $CHECK ]] || die "missing $(rel "$CHECK")"
  bash "$CHECK"
}

action=${1:-status}
shift || true
case "$action" in
  sync) cmd_sync ;;
  run) cmd_run ;;
  status) cmd_status "$@" ;;
  *) usage ;;
esac
